### ISSUE TITLE
Training Time on  the reduced Argoverse dataset

### ISSUE THREAD

**Issue by Son-Goku-gpu** [frankfengdi/LidarMTL#1]
Great work! Frank. I wonder how much time it takes to train your model on the reduce argoverse dataset (as you mentioned you down-sample the dataset by a factor of 5), and how many GPUs and memories you used for the traning. Thanks a lot!

**Comment by frankfengdi** [comment]
Thanks! Using a Titan RTX with batch size 4 takes approximately eight hours and 6-10G RAM for training (depending on voxelization and FOV).
