### ISSUE TITLE
 error while creating Info files

### ISSUE THREAD

**Issue by arsalan311** [frankfengdi/LidarMTL#3]
I am getting this key error

voxels_ground_cls_labels = input_dict['voxels_ground_cls_labels']
        voxels_ground_cls_labels[voxels_ground_cls_labels>0] = 1 # if a point in a voxel is on the ground, all voxel is on the ground
        voxels_ground_reg_labels = input_dict['voxels_ground_reg_labels']

I check in the prep info files. These keys were not assigned
Sorry I am new with this 
I used Argoverse 3D Tracking v1.1 dataset.

**Comment by frankfengdi** [comment]
Dear Arsalan Aftab Sayed, could you please provide more information? For example what is the "prep info files", and point which lines and which files cause the unknown key problem?

**Comment by arsalan311** [comment]
> Dear Arsalan Aftab Sayed, could you please provide more information? For example what is the "prep info files", and point which lines and which files cause the unknown key problem?
Thanks, It worked
I had generated files  for agroverse dataset kitti and not for agroverse dataset lidar augmented (I wanted the model for object detection only). Though I used the correct config.
