### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by arsalan311** [frankfengdi/LidarMTL#4]
[REDACTED]

**Comment by frankfengdi** [comment]
Dear Arsalan Aftab Sayed, we use the Argoverse 3D Tracking v1.1. The dataset worked in our setting. Could you please report the error more clearly (which lines, which variables)?

**Comment by arsalan311** [comment]
> Dear Arsalan Aftab Sayed, we use the Argoverse 3D Tracking v1.1. The dataset worked in our setting. Could you please report the error more clearly (which lines, which variables)?

Thanks. Actually there were some files missing from agroverse api, I believe the version was different earlier so it was getting difficult to generate Info files. I found the compatible version and now It worked.
